### ISSUE TITLE
Cannot close open connections in 11.1.0

### ISSUE THREAD

**Issue by edonosotti** [AndrewBarba/apns2#57]
The suggestions from #29 no longer work in 11.1.0.

`client.destroy()` throws error `TypeError: client.destroy is not a function`.

`client._clients.destroy()` throws error `TypeError: Cannot read properties of undefined (reading 'destroy')`.

The `README` file briefly mentions closing clients ("Once a client is closed you will not be able to use it again."), but no further information is given.

**Comment by AndrewBarba** [comment]
Hey @edonosotti I'm sorry for the delay here. v11 switches to the underlying http client to `fetch-http2` which does not use a connection pool anymore so there isn't anything to close / destroy. I will update the readme.

**Comment by dchahla** [comment]
> The suggestions from #29 no longer work in 11.1.0.
> 
> `client.destroy()` throws error `TypeError: client.destroy is not a function`.
> 
> `client._clients.destroy()` throws error `TypeError: Cannot read properties of undefined (reading 'destroy')`.
> 
> The `README` file briefly mentions closing clients ("Once a client is closed you will not be able to use it again."), but no further information is given.

try using @swoopshops/easy-apn to get the full HTTP log.

**Comment by AndrewBarba** [comment]
Sorry I have to close this due to other spam. Please re-open as needed with questions / concerns.
